name: websocket_chat_app
description: A Flutter WebSocket chat app with clean architecture and BLoC

environment:
  sdk: '^3.9.0<4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  web_socket_channel: ^2.4.0
  get_it: ^7.6.4
  injectable: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  build_runner: ^2.4.7